version: 2
registries:
  maven-google:
    type: maven-repository
    url: https://maven.google.com
    username: ""
    password: ""
updates:
- package-ecosystem: gradle
  directory: "/01_intro/intro"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/02_types/types"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/03_control/fun"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/03_control/if_else"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/03_control/when"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/04_tests/tests"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/05_oop/oop"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/06_oop/oop"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/07_exceptions/exceptions"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/08_collections/collections"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/09_lambda/lambda"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/10_sequence/sequence"
  registries:
      - maven-google
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
